// MusicDB,  a music manager with web-bases UI that focus on music.
// Copyright (C) 2017-2020  Ralf Stemmer <ralf.stemmer@gmx.net>
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

"use strict";

class FileSelect extends Element
{
    // content type: "video", "artwork"
    // annotations: an object with initial annotations
    constructor(labeltext, tooltip, icon, contenttype, accept, annotations=null)
    {
        super("label", ["FileSelect", "flex-row"]);

        this.input = document.createElement("input")
        this.input.type     = "file";
        this.input.accept   = accept;
        this.input.onchange = (event)=>{this.onFileSelected(event);};
        this.icon  = icon;
        this.text  = new Element("span");
        this.text.SetInnerText(labeltext);

        this.contenttype = contenttype;
        if(annotations != null)
            this.annotations = annotations;
        else
            this.annotations = new Object();

        // Unique identifier to distinguish which process got triggered by which selector
        // This ID is allow annotated to the upload task
        this.selectorid = crypto.randomUUID();
        this.annotations["selectorid"] = this.selectorid;


        this.AddCSSClass("flex-row");
        this.SetTooltip(tooltip);

        this.AppendChild(this.icon);
        this.AppendChild(this.text);
        this.AppendChild(this.input);
    }



    // This method returns the task.id of the upload task
    onFileSelected(event)
    {
        let fileinfos = event.target.files[0];
        let name = fileinfos.name;
        let size = Math.ceil(fileinfos.size / (1024*1024)); // in MiB
        let type = fileinfos.type;
        let date = new Date(fileinfos.lastModified);

        window.console && console.log(fileinfos);
        window.console && console.log(name);
        window.console && console.log(size);
        window.console && console.log(type);
        window.console && console.log(date);

        // Start Upload
        let taskid;
        taskid = uploadmanager.UploadFile(this.contenttype, fileinfos, this.annotations);

        // Update Label
        let newlabel = `${name}&nbsp;<span class="hlcolor">${size}&#8239;MiB</span>`;
        this.text.SetInnerHTML(newlabel);

        return taskid;
    }
}



class DirectorySelect extends FileSelect
{
    constructor(labeltext, tooltip, icon, contenttype, accept, annotations=null)
    {
        super(labeltext, tooltip, icon, contenttype, accept, annotations);
        this.input.webkitdirectory = true;
    }



    // This method returns the groupid of the selected files (this ID is annotated to the upload tasks)
    onFileSelected(event)
    {
        let files = event.target.files;
        window.console?.log(files);

        // Calculate the sum of all file sized to get the total upload size
        let size  = 0;
        let count = 0;
        for(let file of files)
        {
            size  += Math.ceil(file.size / (1024*1024)); // in MiB
            count += 1;
        }

        // TODO: In Firefox, there is an object webkitRelativePath that holds "dirname/filename".
        // This can be used to annotate a potential album name.

        // Create identifier for the album.
        // So every individual file/task can be connected to this event of selecting them together.
        // Because it is just a group of files and not yet an album as long as the user does not integrate it
        //  into the music directory, the name goupid is fitting better to its purpose.
        // An albumid is later generated by the MusicDB back end.
        let groupid = crypto.randomUUID();
        this.annotations["groupid"] = groupid;

        // Update Label
        let newlabel = `${count} Files <span class="hlcolor">${size}&#8239;MiB</span>`;
        this.text.SetInnerHTML(newlabel);

        // Trigger Upload
        for(let fileinfos of files)
        {
            uploadmanager.UploadFile(this.contenttype, fileinfos, this.annotations);
        }

        return groupid;
    }
}



class VideoFileSelect extends FileSelect
{
    constructor(labeltext, tooltip)
    {
        super(labeltext, tooltip, new SVGIcon("VideoFile"), "video", "video/*");
    }
}



class ArtworkFileSelect extends FileSelect
{
    // Optional initial annotations. MusicDB requires a "musictype", "musicpath" and "musicid" for artworks
    constructor(labeltext, tooltip, initialannotations=null)
    {
        super(labeltext, tooltip, new SVGIcon("ArtworkFile"), "artwork", "image/*", initialannotations);
    }
}



class AlbumDirectorySelect extends DirectorySelect
{
    constructor(labeltext, tooltip)
    {
        super(labeltext, tooltip, new SVGIcon("MusicDB"), "albumfile", "*");
    }

    onFileSelected(event)
    {
        // To avoid race conditions, do not filter for specific uploads.
        // Just listen to all status updated.
        albumuploadprogress.SetSelectorFilter(this.selectorid);
        albumuploadprogress.ResetUI();
        albumintegrationlayer.SetSelectorFilter(this.selectorid);
        albumintegrationlayer.ResetUI();

        // Start the upload but also show the progress layer for album upload.
        let groupid;
        groupid = super.onFileSelected(event);
        albumuploadprogress.Show();
    }
}


// vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

